architect:
  - meetmangukiya

install:
  - if ! pip3 -V ; then wget -O - https://bootstrap.pypa.io/get-pip.py | sudo python3; fi
  - sudo pip3 install -r requirements.txt

merge:
  fast-forward: only

docker:
  - image: "ubuntu:16.04"
  - script: |
      - sudo apt-get -y update
      - sudo apt-get install -y python3-dev
      - sudo pip3 install --upgrade pip
